### Create Merchant Account.
POST http://localhost:7071/api/create/merchant
Content-Type: application/json

{   
    "paymentProvider": "ADYEN",
    "legalEntityName": "PlanB. GmbH",
    "countryCode": "DE",
    "currency": "EUR",
    "storePaymentMethodMode": [
        "masterCard",
        "Visa"
        ]
}

### Get Merchant Accounts.
GET http://localhost:7071/api/get/merchants


### Update Merchant Account.
PUT http://localhost:7071/api/update/merchant/c56db5bb-eb07-4b72-8d18-0258bbcfc914
Content-Type: application/json

{
    "paymentProvider": "NOPE Hehehe",
    "legalEntityName": "No Name",
    "countryCode": "RU",
    "currency": "EUR",
    "storePaymentMethodMode": [
        "masterCard",
        "Visa"
    ]
}


### Delete Merchant Account.
DELETE http://localhost:7071/api/delete/merchant/c56db5bb-eb07-4b72-8d18-0258bbcfc914
Content-Type: application/json